name: Test PR Creation

on:
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check branch
        if: ${{ github.ref_name != 'main' }}
        run: |
          echo "This workflow can only be run from the main branch."
          exit 1

      - name: Create a new branch
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          BRANCH_NAME="test-branch-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Make changes
        run: |
          UNIQUE_TEXT="This is a test PR created by GitHub Actions on $(date). Triggered by ${{ github.actor }} in run ${{ github.run_id }}."
          echo $UNIQUE_TEXT >> test-file.txt
          git add test-file.txt
          git commit -m "Add test file for PR creation"

      - name: Push the new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin ${{ env.branch_name }}
