name: Test PR Creation

on:
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "This workflow cannot be run from the main branch."
          exit 1

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Create a new branch
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          BRANCH_NAME="test-branch-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Make changes
        run: |
          UNIQUE_TEXT="This is a test PR created by GitHub Actions on. Triggered by ${{ github.actor }} in run."
          echo $UNIQUE_TEXT >> test-file.txt
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit. Exiting workflow."
            exit 0
          else
            git add test-file.txt
            git commit -m "Add test file for PR creation"
          fi

      - name: Push the new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin ${{ env.branch_name }}

      - name: Create a Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Test PR from GitHub Actions" \
            --body "This is a test Pull Request created by GitHub CLI in workflows." \
            --head ${{ env.branch_name }} \
            --base main    
